export const navigationItems = [
  {
    id: 'dashboard',
    label: '대시보드',
    subtitle: 'Overview',
    title: '기본 관리자 대시보드',
    description: '오늘 운영 현황과 주요 지표를 한 번에 확인합니다.',
    sections: ['실시간 지표', '최근 활동', '할 일', '운영 알림'],
    quickActions: ['보고서 보기', '알림 확인', '운영 브리핑'],
    note: '오전 회의 전 KPI 변동과 긴급 문의를 먼저 확인하세요.',
  },
  {
    id: 'orders',
    label: '주문 관리',
    subtitle: 'Orders',
    title: '주문 관리',
    description: '신규 주문, 배송 준비, 환불 요청을 빠르게 처리합니다.',
    sections: ['전체 주문', '배송 준비', '배송 중', '취소/환불'],
    quickActions: ['송장 업로드', '주문 내보내기', '지연 주문 확인'],
    note: '배송 지연 가능 주문이 있는지 오후 2시 전에 확인하세요.',
  },
  {
    id: 'members',
    label: '회원 관리',
    subtitle: 'Members',
    title: '회원 관리',
    description: '회원 상태와 등급, 휴면 예정 대상을 관리합니다.',
    sections: ['전체 회원', 'VIP 회원', '휴면 예정', '주의 계정'],
    quickActions: ['회원 추가', '등급 조정', '휴면 알림 발송'],
    note: '휴면 예정 회원은 프로모션 메시지 대상과 함께 검토하면 좋아요.',
  },
  {
    id: 'products',
    label: '상품 관리',
    subtitle: 'Products',
    title: '상품 관리',
    description: '판매 상품, 재고 현황, 진열 상태를 관리합니다.',
    sections: ['판매 중', '품절 임박', '재입고 예정', '노출 중단'],
    quickActions: ['상품 등록', '재고 수정', '진열 순서 변경'],
    note: '품절 임박 상품은 주간 배너와 연결되어 있는지 함께 확인하세요.',
  },
  {
    id: 'content',
    label: '콘텐츠',
    subtitle: 'Content',
    title: '콘텐츠 운영',
    description: '배너, 공지, 이벤트 콘텐츠를 계획하고 발행합니다.',
    sections: ['배너', '공지사항', '이벤트', '팝업'],
    quickActions: ['콘텐츠 작성', '예약 발행', '검수 요청'],
    note: '메인 배너와 공지의 공개 시간은 고객센터 대응 시간과 맞추는 게 좋아요.',
  },
  {
    id: 'analytics',
    label: '분석',
    subtitle: 'Analytics',
    title: '데이터 분석',
    description: '유입 채널과 전환율, 매출 흐름을 확인합니다.',
    sections: ['유입 채널', '전환 분석', '매출 추이', '이탈 구간'],
    quickActions: ['리포트 생성', 'CSV 다운로드', '주간 비교'],
    note: '전환율 하락은 장바구니 단계와 결제 완료 페이지를 함께 보는 편이 정확합니다.',
  },
  {
    id: 'settings',
    label: '설정',
    subtitle: 'Settings',
    title: '시스템 설정',
    description: '관리자 권한, 연동 서비스, 보안 정책을 관리합니다.',
    sections: ['권한 관리', '알림 설정', '연동 서비스', '보안 정책'],
    quickActions: ['권한 승인', '알림 테스트', '보안 점검'],
    note: '관리자 권한 변경은 로그 기록과 함께 검토하는 것을 권장합니다.',
  },
]
